services:
  shade-agent-app:
    environment:
      AGENT_CONTRACT_ID: ${AGENT_CONTRACT_ID}
      SPONSOR_ACCOUNT_ID: ${SPONSOR_ACCOUNT_ID}
      SPONSOR_PRIVATE_KEY: ${SPONSOR_PRIVATE_KEY}
    platform: linux/amd64
    image: pivortex/shade-agent-template@sha256:7134c5a312bd0c70377bf44b8f68d9fe8045adf8c80955fee7dbd2c36c49bd92
    container_name: shade-agent-app
    ports:
      - 3000:3000
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
    restart: always
