services:
  shade-test-image:
    environment:
      AGENT_CONTRACT_ID: ${AGENT_CONTRACT_ID}
      SPONSOR_ACCOUNT_ID: ${SPONSOR_ACCOUNT_ID}
      SPONSOR_PRIVATE_KEY: ${SPONSOR_PRIVATE_KEY}
    platform: linux/amd64
    image: pivortex/shade-test-image@sha256:974699da87f90d20343f92318bf9ecda67a3535c5eba51d7e227dc8fccea734c
    container_name: shade-test-image
    ports:
      - 3000:3000
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
    restart: always
