services:
  shade-agent-app:
    environment:
      AGENT_CONTRACT_ID: ${AGENT_CONTRACT_ID}
      SPONSOR_ACCOUNT_ID: ${SPONSOR_ACCOUNT_ID}
      SPONSOR_PRIVATE_KEY: ${SPONSOR_PRIVATE_KEY}
    platform: linux/amd64
    image: pivortex/my-first-agent@sha256:ff20a43a6c2c3da676f516437ff849d45324e5b9bf82636ab182b67906392776
    container_name: shade-agent-app
    ports:
      - 3000:3000
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
    restart: always
