services:
  shade-agent-app:
    environment:
      AGENT_CONTRACT_ID: ${AGENT_CONTRACT_ID}
      SPONSOR_ACCOUNT_ID: ${SPONSOR_ACCOUNT_ID}
      SPONSOR_PRIVATE_KEY: ${SPONSOR_PRIVATE_KEY}
    platform: linux/amd64
    image: pivortex/shade-agent-test@sha256:fdbca536451df8e5d791b5e666b9f6b90f5c8701eb5efae7973803b39ac96a50
    container_name: shade-agent-app
    ports:
      - 3000:3000
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    restart: always
